##
## Makefile for Makefile in /home/bache_a/work/perso/Makefile
##
## Made by Antoine Baché
## Login   <bache_a@epitech.net>
##
## Started on  Fri Nov 25 20:10:26 2016 Antoine Baché
## Last update Sun Jan  8 06:36:02 2017 Antoine Baché
##

# Makefile dependencies directory
MK_DIR=		./
MK_COMMON_DIR= 	./

NAME=		cpp_SKL
MODE=
DEBUG=		no

include $(MK_COMMON_DIR)colors.mk $(MK_COMMON_DIR)defs.mk

# Project's files
SRC=		array.c			\
		double.c		\
		exceptions.c		\
		float.c			\
		int16_t.c		\
		int32_t.c		\
		int64_t.c		\
		int8_t.c		\
		list.c			\
		main.c			\
		new.c			\
		operation.c		\
		smart_ptr.c		\
		String.c		\
		test_type.c		\
		uint16_t.c		\
		uint32_t.c		\
		uint64_t.c		\
		uint8_t.c

# Rules
include $(MK_COMMON_DIR)rules.mk
